---
version: '2.3'

services:

  # HTTPD Server
  httpd:
    image: devilbox/nginx-stable:alpine
    build:
      context: ../../Dockerfiles
      dockerfile: Dockerfile.alpine
    hostname: httpd
    environment:
      - NEW_UID=1000
      - NEW_GID=1000
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/default/htdocs
